### ISSUE TITLE
Containerized builds

### ISSUE THREAD

**Issue by maxogden** [browserify/wzrd.in#117]
If anyone wants to wrap the current build process inside Docker (or some other container) that would be awesome and would help with potential security issues. Right now we sort of trust that npm scripts won't do anything bad, but that's pretty bad from a security standpoint. Docker obviously isn't a security panacea, but it is at least better than what we have now.

**Comment by jfhbrook** [comment]
Agreement. This also makes it really easy to do cleanup afterwards.

**Comment by maxogden** [comment]
Awesomeness. I wonder if theres a module that implements the `child_process` api but with docker?
