### ISSUE TITLE
Problem with Async-Await

### ISSUE THREAD

**Issue by entrptaher** [browserify/wzrd.in#184]
URL: https://wzrd.in/standalone/emittery@latest
Package: emittery
```
---FLAGRANT SYSTEM ERROR---

(logs uuid: e640f410-ee6a-11e7-a9f3-adc98ef83082 )

Error: "browserify exited with code 1"

code: 1
stderr: 
/tmp/emittery1171131-12863-wlncp0/node_modules/emittery/index.js:42
	async emit(eventName, eventData) {
       ^
ParseError: Unexpected token

dirPath: /tmp/emittery1171131-12863-wlncp0

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!

```

Can we somehow provide babelify?

**Comment by jfhbrook** [comment]
This project is on hiatus for reasons, but perhaps https://github.com/browserify/wzrd.in/issues/166 ?

**Comment by entrptaher** [comment]
I think if we have to define async-await in actual module, then the usage of wzrd.in fails. Since wzrd.in is there to provide proper `browserify-as-a-service`. Now, how do we resolve the issue, hmm.

**Comment by jfhbrook** [comment]
You could always fork it and fix it, and deploy the new service yourself.

This probably comes across as a "fuck you," but for various reasons it doesn't make sense for me to work on this right now, so you're not going to get this feature out of me.

**Comment by entrptaher** [comment]
Okay. I appreciate the thought.
