### ISSUE TITLE
https://wzrd.in SSL certificate date invalid

### ISSUE THREAD

**Issue by shannonmoeller** [browserify/wzrd.in#185]
https://wzrd.in/standalone/apply-html

![image](https://user-images.githubusercontent.com/155164/35789594-74b06b0e-09fa-11e8-9831-0a1159acd62f.png)

**Comment by shaunlebron** [comment]
FYI: This is causing some notebooks to fail on https://observablehq.com/ due to wzrd.in being recommended for importing modules here:

https://beta.observablehq.com/@tmcw/requiring-modules-troubleshooting

**Comment by shannonmoeller** [comment]
Issue has been resolved. Thanks @jfhbrook!
