### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by harrysarson** [browserify/wzrd.in#186]
https://wzrd.in/ seems to be down.

I am getting a 502 Bad Gateway when I try and navigate there.

**Comment by colinmegill** [comment]
Same, still: 

![image](https://user-images.githubusercontent.com/1770265/37997146-ef698c1c-31ce-11e8-82e0-3dfbf0def74d.png)

**Comment by jfhbrook** [comment]
if anyone in the @browserify/owners org wants ssh access to peep this, I can facilitate. Too busy to dig into it myself otherwise--sorry!

**Comment by mpj** [comment]
For the future, some step-by-step directions on how to self-host this would be nice.

**Comment by jfhbrook** [comment]
@mpj I gotcha https://github.com/browserify/wzrd.in#installationoperation devops not included

**Comment by goto-bus-stop** [comment]
I dont have time anymore today but I can check tomorrow or if something like this happens again in the future. Do you just need an SSH pubkey?

**Comment by jfhbrook** [comment]
@goto-bus-stop yes, I just need an ssh pubkey.

**Comment by goto-bus-stop** [comment]
@jfhbrook 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIcqLr2k2uUw7VwPIiG0J/iHolQoIA4F+Dv9BVZdvzhWrwj3v2rVYi7SCPi2Ffe4A46xWsUXIwnKcVWET3ck3GyC95TnR4YW/fU6imabIm2V1xmhOo79cartT+bbcsXaTMpDAWpuKl6J6S9TpF07+wLJmmePBrZ2nZRHOUT+2+t1OFzFmFmC071G+nztu4+KZirgAEDLsXPBnRj2DGz+NNyJoBgqRlbsrrkzjwZHaYSK5tLDRP8OYqwgghyl3BzFncqFYgjaNa2mz5EGiwXHy8rVzlVnu2ImcmF7xvRF3IGukgdE0ryw2cC5fI+WdEcNscBNs8c/1EV44ci+gaopY1 renee@kooi.me
```

**Comment by jfhbrook** [comment]
@goto-bus-stop ok cool, you're added. `admin@wzrd.in` go to town! I'm camping the #browserify irc if you have questions.

**Comment by goto-bus-stop** [comment]
Thanks! I just did `mongroup restart` and it looks like it's back up for now.

**Comment by jfhbrook** [comment]
gg. Most of the issues I've ran into have been related either to the cache getting too big, the logs not getting rotated properly, a combination of those two, or the letsencrypt cron job quietly breaking. :) I think I fixed the cron job finally and I haven't had logs issues lately, so I think we're actually ok!

**Comment by jfhbrook** [comment]
I think the biggest challenge ops-wise is that it's just a single machine that max is paying for afaik and no configuration mgmt/etc, so doing architectural changes can be a bit of a thing. I was always a fan of using load balancers to shift traffic onto new instances, which is a strategy that won't work here, barring somebody setting up a shared account being paid for by donations or something. Still, if left alone, minus hiccups like this it should keep trucking as always.

**Comment by b0o** [comment]
@jfhbrook @goto-bus-stop Website is down again :disappointed:

**Comment by goto-bus-stop** [comment]
Thanks for the ping; the letsencrypt SSL certificate expired, just 
renewed it!

**Comment by jfhbrook** [comment]
LE should auto-renew, I think the permissions on the files the cron job is trying to write to are fucky.

I was just never able to properly test it, is all.
