### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by patrickxchong** [browserify/wzrd.in#199]
https://wzrd.in loads up. But when one tries to get a package from wzrd.in, eg: https://wzrd.in/standalone/axios@latest, it returns a 502 bad gateway error. I noticed the issue 1 day ago around 10am EST and have been trying every couple of hours to see if the feature would go live again or not.

**Comment by chiawendt** [comment]
@goto-bus-stop

**Comment by goto-bus-stop** [comment]
appears to work again after a server restart, thanks for the ping & sorry for the trouble!

**Comment by dahjah** [comment]
Looks like this may be down again.

**Comment by goto-bus-stop** [comment]
likely :( the problem is that npm installs put some temporary data in /tmp and the disk keeps filling up. i gotta set up a cron job to fix that, apparently the npm `--no-cache` flag doesn't do the trick

**Comment by DominicMaas** [comment]
Just discovered this service, seems to be happening again.

**Comment by Kirysha** [comment]
@goto-bus-stop seems to need to restart, https://wzrd.in/standalone/raf@latest, it returns a 502 bad gateway error
